//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncripcionesCobach
{
    using System;
    
    public partial class sp_GetCostoPlantel_Result12
    {
        public string Plantel { get; set; }
        public int idPlantel { get; set; }
        public int Matricula { get; set; }
        public string NombreCompleto { get; set; }
        public int CveGrupo { get; set; }
        public int NoAcreditadas { get; set; }
        public bool pagoInscripcion { get; set; }
        public bool pagoSA { get; set; }
        public int idCostos { get; set; }
        public string PlantelNum { get; set; }
        public string CIE { get; set; }
        public Nullable<int> Inscripcion { get; set; }
        public Nullable<int> SociedadAlumnos { get; set; }
        public string TM { get; set; }
        public string TV { get; set; }
        public Nullable<int> idMatricula { get; set; }
        public Nullable<int> Referencia { get; set; }
    }
}
