//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncripcionesCobach
{
    using System;
    
    public partial class sp_GetCostoPlantel_Result6
    {
        public string Plantel { get; set; }
        public string idPlantel { get; set; }
        public string Matricula { get; set; }
        public string NombreCompleto { get; set; }
        public string CveGrupo { get; set; }
        public Nullable<bool> pagoInscripcion { get; set; }
        public Nullable<bool> pagoSociedadAlumnos { get; set; }
        public int idCostos { get; set; }
        public string PlantelNum { get; set; }
        public string CIE { get; set; }
        public Nullable<int> Inscripcion { get; set; }
        public Nullable<int> SociedadAlumnos { get; set; }
        public Nullable<int> idMatricula { get; set; }
        public Nullable<int> Referencia { get; set; }
    }
}
